### PR TITLE
Stop using Circle CI

### PR DESCRIPTION
**Pull request by iamed2**
It was an experiment that required maintaining our own docker images. Let's not do that.

### CODE REVIEW

**Review by ararslan — APPROVED** [review]
I wasn't around when you introduced Circle builds here, but this seems reasonable to me, for whatever that's worth.

**Comment by ararslan** [comment]
Just gotta flip the switch in the Circle config to tell it to stop building

**Comment by iamed2** [comment]
Already did

**Comment by ararslan** [comment]
Oh MAN it is PARTY TIME now.

**Pull request merged**
